config/routes.rb
Tunerie::Application.routes.draw do
    match 'tuner(/index.:format)' => 'tuner#index', :as => :tuner
    match 'tuner/channel/:device_address/:tuner_address(/:channel_name)'  => 'tuner#channel', :as => :channel
    match 'tuner/channel/:device_address/:tuner_address(.:format)'  => 'tuner#channel', :as => :channel
    match 'tuner/target/:device_address/:tuner_address(/:target_address)' => 'tuner#target', :as => :target
    match 'tuner/get_player_status' => 'tuner#get_player_status', :as => :get_player_status
    match 'tuner/target_player/:player_address(/:content_address)' => 'tuner#target_player', :as => :target_player
    match 'tuner/playback_track/:player_address/:id' => 'tuner#playback_track', :as => :playback_track
    match 'tuner/tune_up/:device_address/:tuner_address' => 'tuner#tune_up', :as => :tune_up
    match 'tuner/tune_down/:device_address/:tuner_address' => 'tuner#tune_down', :as => :tune_down
    match 'tuner/setup' => 'tuner#setup', :as => :setup

    root :to => 'tuner#index'
end

app/models/tuner.rb
class Tuner < ActiveRecord::Base
    belongs_to :device
    has_many   :channels

    def current_target()
        %x[hdhomerun_config #{device.ip_address} get /#{address}/target].strip
    end

    def current_frequency()
        %x[hdhomerun_config #{device.ip_address} get /#{address}/channel].strip
    end

    def current_program()
        %x[hdhomerun_config #{device.ip_address} get /#{address}/program].strip
    end

    def current_channel_name()
        frequency = %x[hdhomerun_config #{device.ip_address} get /#{address}/channel].strip
        program   = %x[hdhomerun_config #{device.ip_address} get /#{address}/program].strip
        channel   = channels.find_by_frequency_and_program_id(frequency, program)

        channel ? channel.name : 'none'
    end

    def current_channel_alias()
        frequency = %x[hdhomerun_config #{device.ip_address} get /#{address}/channel].strip
        program   = %x[hdhomerun_config #{device.ip_address} get /#{address}/program].strip
        channel   = channels.find_by_frequency_and_program_id(frequency, program)

        if channel then
            if channel.alias then
                unless channel.alias.empty? then
                    channel.alias
                end
            end
        end
    end

    def next_channel()
        current_channel = channels.find_by_name(current_channel_name)
        current_channel ? (channels[channels.index(current_channel) + 1] || channels[0]) : nil
    end

    def previous_channel()
        current_channel = channels.find_by_name(current_channel_name)
        current_channel ? channels[channels.index(current_channel) - 1] : nil
    end

    def tune_up()
        tune_to(next_channel.name)
    end

    def tune_down()
        tune_to(previous_channel.name)
    end

    def tune_to(channel_name)
        request = channels.find_by_name(channel_name)

        command = <<-eos
hdhomerun_config #{device.ip_address} set /#{address}/channel none;
hdhomerun_config #{device.ip_address} set /#{address}/channel #{request.frequency};
hdhomerun_config #{device.ip_address} set /#{address}/program #{request.program_id};
        eos

        %x[#{command}]
    end

    def stream_to(target_address)
        ip, port = target_address.strip.split(':')

        if port then
            begin
                Integer(port)
                
                if ip.match /\A(?:25[0-5]|(?:2[0-4]|1\d|[1-9])?\d)(?:\.(?:25[0-5]|(?:2[0-4]|1\d|[1-9])?\d)){3}\z/ then
                    %x[hdhomerun_config #{device.ip_address} set /#{address}/target #{ip}:#{port}]
                    return true
                else
                    puts "Incorrect target address #{params[:target_address]}..."
                end
            rescue
                puts "Incorrect parameter #{params[:target_address]}..."
            end
        end

        return false
    end

    def self.status(device_address, tuner_address)
        status = []

        status.push %x[hdhomerun_config #{device_address} get /#{tuner_address}/status].strip.split
        status.push %x[hdhomerun_config #{device_address} get /#{tuner_address}/target].strip.split

        status
    end

    def self.scan(device_address, tuner_address)
        output_filename = "db/data/#{device_address}-#{tuner_address}-channels-#{Time.now.strftime('%Y%m%d-%H%M%S')}"
        scan_filename   = "#{output_filename}.txt"
        data_filename   = "#{output_filename}.yml"
        tuner_id        = tuner_address.sub('tuner', '')

        %x[hdhomerun_config #{device_address} scan #{tuner_id} #{scan_filename}].strip

        if $?.success? then
            %x[lib/process_scan.rb #{scan_filename} > #{data_filename}]

            load "#{RAILS_ROOT}/Rakefile"

            Rake::Task["tunerie:initialize_devices" ].invoke
            Rake::Task["tunerie:remove_channels_of" ].invoke(device_address, tuner_address)
            Rake::Task["tunerie:import_channels_for"].invoke(device_address, tuner_address, data_filename)
        end
    end
end

app/controllers/tuner_controller.rb
class TunerController < ApplicationController
    before_filter :find_device, :setup_growl, :except => [ :index, :setup ]

    def index()
        @devices = Device.all
        @players = Player.all

        respond_to do |format|
            format.html
        end
    end

    def target()
        if params[:target_address] then
            if @tuner.stream_to(params[:target_address]) then
                notify "#{params[:target_address]}"
                redirect_to channel_url
                return
            end
        end

        refresh_program_info

        respond_to do |format|
            format.html
        end
    end

    def channel()
        @tuner.tune_to(params[:channel_name]) if params[:channel_name]
        refresh_program_info
        notify "#{@channel.alias || @channel_name}" if params[:channel_name]

        respond_to do |format|
            format.html
        end
    end

    def tune_up()
        @tuner.tune_up
        redirect_to channel_url
    end

    def tune_down()
        @tuner.tune_down
        redirect_to channel_url
    end

    def setup()
        @discovered = Device.discover

        respond_to do |format|
            format.html
        end
    end

    private

    def find_device()
        @device_address = params[:device_address]
        @tuner_address  = params[:tuner_address]
        @device         = Device.find_by_address(@device_address)
        @tuner          = @device.tuners.find_by_address(@tuner_address)
        @channels       = @tuner.channels
    end

    def refresh_program_info()
        @target        = @tuner.current_target
        @frequency     = @tuner.current_frequency
        @program       = @tuner.current_program
        @channel       = @channels.find_by_frequency_and_program_id(@frequency, @program)
        @channel_name  = @channel ? @channel.name  : ''
        @channel_alias = @channel ? @channel.alias : ''
    end

    def setup_growl()
        if GROWL_CONFIG['send_notifications'] then
            @growl = Growl.new GROWL_CONFIG['server'], application_name.downcase, [ "#{application_name} Notifications" ], [ "#{application_name} Notifications" ], GROWL_CONFIG['password']
        end
    end

    def notify(message)
        @growl.notify("#{application_name} Notifications", application_name, message) if @growl
    end
end

app/views/tuner/_global_footer.html.erb
<div>open source software by <a href='http://twitter.com/#!/madhckr' target='_blank'>@madhckr</a></div>

app/views/tuner/channel.html.erb
<script>
$(document).ready(function() {
    $('li[title]').qtip({
        content:  { title: { text: 'Channel information', button: false } },
        position: { my: 'top left', at: 'bottom left' },
        style:    { classes: 'ui-tooltip-shadow ui-tooltip-dark' },
        show:     { event: 'click', solo: true, effect: function() { $(this).slideDown(100); } },
        hide:     { event: 'click', effect: function() { $(this).slideUp(100); } }
    })
});
</script>

<% 
pc = @tuner.previous_channel
nc = @tuner.next_channel

pc ?
    (pc_name, pc_alias = pc.name, (pc.alias && !pc.alias.empty?) ? " / #{pc.alias}" : '') :
    (pc_name, pc_alias = 'none', '')

nc ?
    (nc_name, nc_alias = nc.name, (nc.alias && !nc.alias.empty?) ? " / #{nc.alias}" : '') :
    (nc_name, nc_alias = 'none', '')

c_name = 'none'

if @channel_name then
    unless @channel_name.empty? then
        c_name = @channel_name
    end
end

c_alias = ''

if @channel_alias then
    unless @channel_alias.empty? then
        c_alias = " / #{@channel_alias}"
    end
end
%>

<div class='dialog_dark'>
    <div class="hd"><div class="c"></div></div>
    <div class="bd">
        <div class="c">
            <div class="s">
                <ul class='infobox device'>
                    <li>HDHomeRun <%= "#{@device_address} / #{@tuner_address} at #{@device.ip_address}" %></li>
                    <li>
						<ul>
							<li><a href='<%= url_for :controller => 'tuner', :action => 'target', :device_address => @device_address, :tuner_address => @tuner_address %>'>Viewed by <%= "#{@target}" %></a></li><li>Click to change streaming target</li>
					    </ul>
					</li>
                    <li>
						<ul>
							<li class='channel_navigator'>
								<span><a href='<%= url_for :controller => 'tuner', :action => 'tune_down' %>'>Previous</a></span>
								<span>&bull;</span>
								<span><a href='<%= url_for :controller => 'tuner', :action => 'channel', :device_address => @device_address, :tuner_address => @tuner_address %>'>Channels</a></span>
								<span>&bull;</span>
								<span><a href='<%= url_for :controller => 'tuner', :action => 'tune_up' %>'>Next</a></span>
							</li>
							<li class='current_channel'>Current is <%= c_name %><%= c_alias %></li>
							<li>Previous is <%= pc_name %><%= pc_alias %></li>
							<li>Next is <%= nc_name %><%= nc_alias %></li>
					    </ul>
					</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="ft"><div class="c"></div></div>
</div>

<h2>Channel lineup</h2>

<div class='dialog_light'>
    <div class="hd"><div class="c"></div></div>
    <div class="bd">
        <div class="c">
            <div class="s">
                <ul class='infobox lineup'>

				<% if @channels.count > 0 %>

                <% @channels.each do |channel| %>
                    <li title='<%= "<div>#{channel.alias}</div><div>#{channel.description}</div><div></div>" %>'>
						<span class='channel_entry'>
							<a class='noeffect' href='<%= url_for :controller => 'tuner', :action => 'channel', :device_address => @device_address, :tuner_address => @tuner_address, :channel_name => channel.name %>'>
								<span><%= channel.name %></span>
								<span class='channel_alias <%= 'dimmed' if !channel.alias%>'><%= channel.alias || 'Untitled' %></span>
							</a>
						</span>
					</li>
                <% end %>

				<% else %>
					<li><a href='<%= setup_url %>'>Configure device, tuners, and channels</a></li>
				<% end %>

                </ul>
            </div>
        </div>
    </div>
    <div class="ft"><div class="c"></div></div>
</div>

app/views/tuner/channel.json.erb
<%=
raw [ 'device_address' => @device_address, 'tuner_address' => @tuner_address, 'channels' => @channels ].to_json :except => [ :id, :tuner_id, :created_at, :updated_at ]
%>

app/views/tuner/channel.xml.erb
<%=
raw [ 'device_address' => @device_address, 'tuner_address' => @tuner_address, 'channels' => @channels].to_xml :except => [ :id, :tuner_id, :created_at, :updated_at ]
%>

app/views/tuner/index.html.erb
<div class='dialog_dark'>
    <div class="hd"><div class="c"></div></div>
    <div class="bd">
        <div class="c">
            <div class="s">
				<% if @devices.count > 0 then %>

                <% @devices.each do |device| %>
                <ul class='infobox device'>
                    <li><span>HDHomeRun <%= device.address %> at <%= device.ip_address %></span></li>
                    <% device.tuners.each do |tuner| %>
                    <% viewer = tuner.current_target || 'no one' %>
                    <li><span><ul><li><a href='<%= url_for :controller => 'tuner', :action => 'channel', :device_address => device.address, :tuner_address => tuner.address %>'><%= tuner.address %> set on channel <%= tuner.current_channel_name %><%= " / #{tuner.current_channel_alias}" if tuner.current_channel_alias %></a></li><li>Viewed by <%= viewer %></li></ul></span></li>
                    <% end %>
                </ul>
                <% end %>

				<% else %>

                <ul class='infobox device'>
                    <li><span>HDHomeRun</span></li>
					<li><a href='<%= setup_url %>'>Configure device, tuners, and channels</a></li>
				</ul>

				<% end %>
            </div>
        </div>
    </div>
    <div class="ft"><div class="c"></div></div>
</div>

app/views/tuner/index.json.erb
<%= 
raw @devices.collect { |device| [ 'device' => device, 'tuners' => device.tuners ] }.to_json :except => [ :id, :device_id, :tuner_id, :created_at, :updated_at ]
%>

app/views/tuner/index.xml.erb
<%= 
raw @devices.collect { |device| [ 'device' => device, 'tuners' => device.tuners ] }.to_xml :except => [ :id, :device_id, :tuner_id, :created_at, :updated_at ]
%>

app/views/tuner/setup.html.erb
<div class='dialog_dark'>
	<div class="hd"><div class="c"></div></div>
	<div class="bd">
		<div class="c">
			<div class="s">
				<ul class='infobox device'>
					<li><span>HDHomeRun <%= @discovered['device_address'] %> at <%= @discovered['device_ip_address'] %></span></li>
					<% (0..(@discovered['tuners_count'] - 1)).each do |index| %>
					<% 
						 tuner_name   = "tuner#{index}" 
						 tuner_status = Tuner.status(@discovered['device_address'], tuner_name)
					   %>
					<li>
						<ul>
							<li><a href=''>Scan <%= "#{tuner_name}" %> for channels</a></li>
							<% if tuner_status then %>
							<li>Status is <%= tuner_status[0] %></li>
							<li>Target is <%= tuner_status[1] %></li>
							<% else %>
							<li>Unable to retrieve status</li>
							<% end %>
						</ul>
					</li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
	<div class="ft"><div class="c"></div></div>
</div>

app/views/tuner/target.html.erb
<% 
pc = @tuner.previous_channel
nc = @tuner.next_channel

pc ?
    (pc_name, pc_alias = pc.name, (pc.alias && !pc.alias.empty?) ? " / #{pc.alias}" : '') :
    (pc_name, pc_alias = 'none', '')

nc ?
    (nc_name, nc_alias = nc.name, (nc.alias && !nc.alias.empty?) ? " / #{nc.alias}" : '') :
    (nc_name, nc_alias = 'none', '')

c_name = 'none'

if @channel_name then
    unless @channel_name.empty? then
        c_name = @channel_name
    end
end

c_alias = ''

if @channel_alias then
    unless @channel_alias.empty? then
        c_alias = " / #{@channel_alias}"
    end
end
%>

<div class='dialog_dark'>
    <div class="hd"><div class="c"></div></div>
    <div class="bd">
        <div class="c">
            <div class="s">
                <ul class='infobox device'>
                    <li>HDHomeRun <%= "#{@device_address} / #{@tuner_address} at #{@device.ip_address}" %></li>
                    <li>
						<ul>
							<li><a href='<%= url_for :controller => 'tuner', :action => 'target', :device_address => @device_address, :tuner_address => @tuner_address %>'>Viewed by <%= "#{@target}" %></a></li><li>Change streaming target with the form below</li>
					    </ul>
					</li>
                    <li>
						<ul>
							<li class='channel_navigator'>
								<span><a href='<%= url_for :controller => 'tuner', :action => 'tune_down' %>'>Previous</a></span>
								<span>&bull;</span>
								<span><a href='<%= url_for :controller => 'tuner', :action => 'channel', :device_address => @device_address, :tuner_address => @tuner_address %>'>Channels</a></span>
								<span>&bull;</span>
								<span><a href='<%= url_for :controller => 'tuner', :action => 'tune_up' %>'>Next</a></span>
							</li>
							<li class='current_channel'>Current is <%= c_name %><%= c_alias %></li>
							<li>Previous is <%= pc_name %><%= pc_alias %></li>
							<li>Next is <%= nc_name %><%= nc_alias %></li>
					    </ul>
					</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="ft"><div class="c"></div></div>
</div>

<h2>Streaming target</h2>

<%
current_target = (!@target.eql? 'none') ? @target.sub("udp://", '') : "#{request.remote_ip}:1234"
%>

<div class='centered instructions'>
    <div>As the target, enter, for example: <%= current_target %></div>
    <div>On the VNC client, open the stream at: udp://@:1234/</div>
</div>

<div class='dialog_light'>
    <div class="hd"><div class="c"></div></div>
    <div class="bd">
        <div class="c">
            <div class="s">
                <ul class='infobox target'>
                <% form_tag(target_url, :method => 'get') do %>
            	<fieldset>
            		<div class='field  centered'><%= text_field_tag :target_address, current_target %></div>
            		<div class='action centered'><%= submit_tag 'Stream' %></div>
            	</fieldset>
                <% end %>
                </ul>
            </div>
        </div>
    </div>
    <div class="ft"><div class="c"></div></div>
</div>